upload:
    path: /upload
    controller: App\Controller\GeneratorController::index
  
login:
    path: /admin/login
    controller: App\Controller\TestingController::login

home:
    path: /admin/home
    controller: App\Controller\HomeController::init
    
inventory:
    path: /admin/inventory
    controller: App\Controller\TestingController::index
    
purchases:
    path: /admin/purchases
    controller: App\Controller\TestingController::index
    
activations:
    path: /admin/activations
    controller: App\Controller\ActivationController::index
    
credit_notes:
    path: /admin/credit
    controller: App\Controller\NoteController::index
    
configuration:
    path: /admin/configuration
    controller: App\Controller\TestingController::index

testHome:
    path: /test
    controller: App\Controller\TestingController::home

up:
    path: /up
    controller: App\Controller\PurchaseController::upload