generate:
    path: /admin/generate
    controller: App\Controller\GeneratorController::generateExcel
  
login:
    path: /admin/login
    controller: App\Controller\HomeController::login

logout:
    path: /admin/logout
    controller: App\Controller\HomeController::logout

home:
    path: /admin/home
    controller: App\Controller\HomeController::index
    
warehouse:
    path: /admin/warehouse
    controller: App\Controller\WarehouseController::index
    
purchases:
    path: /admin/purchases
    controller: App\Controller\PurchaseController::index
    
activations:
    path: /admin/activations
    controller: App\Controller\ActivationController::index
    
notes:
    path: /admin/credit
    controller: App\Controller\NoteController::index
    
settings:
    path: /admin/settings
    controller: App\Controller\SettingsController::index

testHome:
    path: /test
    controller: App\Controller\TestingController::generateData

up:
    path: /up
    controller: App\Controller\PurchaseController::upload

default:
    path: /{path}
    controller: App\Controller\HomeController::default
    requirements:
        path: .*