upload:
    path: /upload
    controller: App\Controller\GeneratorController::index

testing:
    path: /testing
    controller: App\Controller\TestingController::test

testLogin:
    path: /login
    controller: App\Controller\TestingController::login

activation:
    path: /activations
    controller: App\Controller\ActivationController::index