upload:
    path: /upload
    controller: App\Controller\GeneratorController::index
  
login:
    path: /admin/login
    controller: App\Controller\TestingController::login

home:
    path: /admin/home
    controller: App\Controller\HomeController::index
    
warehouse:
    path: /admin/warehouse
    controller: App\Controller\WarehouseController::index
    
purchases:
    path: /admin/purchases
    controller: App\Controller\PurchaseController::index
    
activations:
    path: /admin/activations
    controller: App\Controller\ActivationController::index
    
notes:
    path: /admin/credit
    controller: App\Controller\NoteController::index
    
settings:
    path: /admin/settings
    controller: App\Controller\TestingController::index

testHome:
    path: /test
    controller: App\Controller\TestingController::generateUser

up:
    path: /up
    controller: App\Controller\PurchaseController::upload